server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:5433/subscription-tracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}