blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/AndriiSynytsia/subscription-tracker/tree/main/docs
    about: Check the documentation before creating an issue