server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  application:
    name: expense-service
  datasource:
    url: jdbc:postgresql://localhost:5433/subscription-tracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}