server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  application:
    name: expense-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/subscription-tracker
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 2
      connection-timeout: 20000