server:
  port: 8088
  error:
    include-message: never
    include-binding-errors: never

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: subscription-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/subscriptions/**
          filters:
              - StripPrefix=1
              - name: AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "${ALLOWED_ORIGINS}:http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.keyn_bello.subscription_tracker: INFO
    org.springframework.cloud.gateway: DEBUG