server:
  port: 8088

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: subscription-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/subscriptions/**
          filters:
              - StripPrefix=1
              - name: AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
jwt:
  secret: ${JWT_SECRET}