server:
  port: 8085
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/subscription-tracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}